### PR TITLE
Add BigInt

### PR DESCRIPTION
**Pull request by plajjan**
This push changes the type int to contain arbitrary size integers, built on BSDNT. It is not ready for merging yet, for several reasons:

- the BSDNT library is not yet incorporated into the build framework. I guess that this will happen soon.

- serialisation does not work. It has to be changed for int, and since many builtin types have an int component, those do not work, either. I have problems in testing serialisation; there is some test code in builtin/serialization_tests, but it seems to be outdated. Has someone tested serialisation recently in some way?

- less important is that formatted output does not work for ints. I have tried to look at the code in CodeGen.hs, but find it difficult. What must be accomplished is that the code cannot anymore access the long value of a variable n : int using n->val, but must do from$int(n). So this is simple once one understands function castLit. Johan?

I push this now anyhow, since there are several things to discuss. First, I should say that most things work well. All tests in the test suite pass, and I have been able to compute the value of e (the base of the natural logarithms) to 10000 decimals (or, rather and equivalently, computed the value of e*10^10000 as an int). On the other hand, integer computations that only need 64 bits become slower, naturally.

As it stands now, I followed Kristian’s suggestion and let int be the default integer type. So far, I have also i64, but the other bounded types should be very simple to add. The problem is that, as it stands, i64 is a rather useless type. To make it useful, I think one needs to change several of our protocols and change parameter types from int to Integral. I am thinking of indexing and slicing, but also lengths of Collections, and others. Not only protocols should change, but also e.g. range. I think that this is also easy, but tedious. I believe that the type checker does not need to change, but the protocol instances become more complicated. This will affect both complexity of the generated C code and the speed of execution. But
- Acton coding with bounded types will be simpler; by a signature for just one variable, the default will be overruled and all computations done in a bounded type.
- in the not too distant future I hope we will be able to simplify generated code, and often remove witnesses altogether.
- in the a bit more distant future, we may be able to sometimes eliminate boxing altogether, and achieve C speed for bounded integer arithmetic.

So, I recommend to do this change, but that could come later. We could start by letting  int be a non-bounded type very soon and gain experience.

Another, related, issue is subtyping of integer types. As of now, i64 is not a subtype of int. This could not be handled by implicit coercion; an int is a pointer to a struct consisting of
- an array of unsigned longs.
- a size field which also codes for sign (a negative size for negative numbers).
- a field which gives the allocated size of the array (one may have allocated a bigger array than necessary (BSDNT ints are mutable; incremental updates (+= etc) really updates the first operand)).

As for i64, i32, i16 etc, I get headache by just considering how subtyping would work with endianness, memory allocation for structs, C code, etc.

Finally, I have not implemented Logical for int. This is not supported in BSDNT’s high level interface zz, but only in the lower level nn. It would be possible, but I tend to think that logical operations are better suited for bounded ints. If someone attempts, a “not implemented” message could suggest to work with a bounded type.

Comments of any of these issues are welcome!

### CODE REVIEW

**Comment by plajjan** [comment]
@sydow I've added bsdnt, which is already merged to main (to reduce risk of git conflicts between this branch and others, since that PR makes lots of changes to build infrastructure). The 146-bigint branch is rebased on that and I also noticed I didn't "back out" enough commits when you and I did interactive rebasing on the call before but I've fixed that now.

Thus for you to continue, remove your local branch entirely and check this one out:
```
git checkout main
git branch -D 146-bigint
git pull
git checkout 146-bigint
git log
```

output should be 
```
commit d629090e0e9f560c9725237eff1f677a01202dbb (HEAD -> 146-bigint, origin/146-bigint)
Author: Björn von Sydow <bjorn.von.sydow@gmail.com>
Date:   Thu Oct 20 14:08:18 2022 +0200

    fixed minor bug in dict_impl.c

commit 1c01ed30dd1cad69d1591edb0222079a9232a40c
Author: Björn von Sydow <bjorn.von.sydow@gmail.com>
Date:   Thu Oct 20 13:40:27 2022 +0200

    Add arbitrary sized ints
    
    Previous int is now i64.

commit 0647df7dd4ffe4d5a62fb7e279def065ba77f6bf (origin/main, origin/HEAD, main)
Merge: 596ff3edd 86af149c1
Author: Kristian Larsson <kristian@spritelink.net>
Date:   Fri Oct 21 15:21:45 2022 +0200

    Merge pull request #991 from actonlang/add-bsdnt
    
    Add bsdnt for bigint support

```

i.e. note how the third commit is my addition of bsdnt support. Then you should be good to go!

**Comment by sydow** [comment]
Hi Kristian.

I did as you suggested and got the log as you predicted. Then I did make, and copy below the lengthy output.

Best

Björn
acton> make
cd compiler && stack build --dry-run 2>&1 | grep "Nothing to build" || \
		(sed 's,^version:.*,version:      "0.11.7.20221021.15.46.24",' < package.yaml.in > package.yaml \
		&& stack build --ghc-options -j4 \
		&& stack --local-bin-path=. install 2>/dev/null)
acton> configure (exe)
Configuring acton-0.11.7.20221021.15.46.24...
acton> build (exe)
Preprocessing executable 'actonc' for acton-0.11.7.20221021.15.46.24..
Building executable 'actonc' for acton-0.11.7.20221021.15.46.24..
[ 8 of 31] Compiling Acton.CommandLineParser
[ 9 of 31] Compiling Paths_acton
[10 of 31] Compiling Acton.Builtin
[11 of 31] Compiling Acton.Prim
[29 of 31] Compiling Acton.CodeGen
[31 of 31] Compiling Main
Linking .stack-work/dist/aarch64-osx/Cabal-3.2.1.0/build/actonc/actonc ...
acton> copy/register
Installing executable actonc in /Users/sydow/acton/compiler/.stack-work/install/aarch64-osx/c0a61ca3b9d848a424af2019a052e93294f3ff541273ae429a5b30cf4ff52996/8.10.7/bin
cp compiler/actonc dist/bin/actonc.tmp
mv dist/bin/actonc.tmp dist/bin/actonc
dist/bin/actonc --always-build builtin/ty/src/__builtin__.act
Building project in /Users/sydow/acton/builtin/ty
  Compiling __builtin__.act for release in stub mode
   Finished compilation in   0.133 s
cp builtin/ty/out/types/__builtin__.ty dist/types/__builtin__.ty
cp builtin/Iterator.h dist/builtin/Iterator.h
cp builtin/__builtin__.h dist/builtin/__builtin__.h
cp builtin/atom.h dist/builtin/atom.h
cp builtin/builtin.h dist/builtin/builtin.h
cp builtin/class_hierarchy.h dist/builtin/class_hierarchy.h
cp builtin/common.h dist/builtin/common.h
cp builtin/complx.h dist/builtin/complx.h
cp builtin/dict.h dist/builtin/dict.h
cp builtin/exceptions.h dist/builtin/exceptions.h
cp builtin/float.h dist/builtin/float.h
cp builtin/hash.h dist/builtin/hash.h
cp builtin/i64.h dist/builtin/i64.h
cp builtin/int.h dist/builtin/int.h
cp builtin/none.h dist/builtin/none.h
cp builtin/range.h dist/builtin/range.h
cp builtin/serialize.h dist/builtin/serialize.h
cp builtin/set.h dist/builtin/set.h
cp builtin/str.h dist/builtin/str.h
cp builtin/tuple.h dist/builtin/tuple.h
ls deps/libbsdnt >/dev/null 2>&1 || git clone https://github.com/wbhart/bsdnt.git deps/libbsdnt
Cloning into 'deps/libbsdnt'...
remote: Enumerating objects: 4199, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 4199 (delta 0), reused 0 (delta 0), pack-reused 4198
Receiving objects: 100% (4199/4199), 987.52 KiB | 3.36 MiB/s, done.
Resolving deltas: 100% (2540/2540), done.
mkdir -p deps/instdir/lib/
cd deps/libbsdnt \
	&& git checkout 97053f366618b0e987a76bc6d6992165c8ea843e \
	&& ./configure --prefix=/Users/sydow/acton/deps/instdir --enable-static --disable-shared CFLAGS="" \
	&& make -j && make install
Note: switching to '97053f366618b0e987a76bc6d6992165c8ea843e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 97053f3 Merge pull request #21 from fredrik-johansson/smallfix
BSDNT Unix Build Script.
BSDNT is a BSD-Licensed Bignum Library.
BSDNT is Copyright (C) its contributors. See LICENSE.
=====================================================
Examining source
Creating Makefile 
Done. 
 
Type make to build this library. We strongly recommend you run 
make check and ensure all tests pass.
    CC     build/helper.o
    CC     build/nn.o
    CC     build/nn_subquadratic.o
    CC     build/nn_quadratic.o
    CC     build/rand/mt.o
    CC     build/rand/kiss.o
    CC     build/nn_linear.o
    CC     build/rand/rand.o
    CC     build/rand/skiss.o
    CC     build/sha1.o
    CC     build/test.o
    CC     build/zz.o
    CC     build/zz0.o
    LINK   build/test/t-rand
    LINK   build/test/t-nn_quadratic
    LINK   build/test/t-nn_subquadratic
    LINK   build/test/t-nn
    LINK   build/test/t-nn_linear
    LINK   build/test/t-zz
    AR     libbsdnt.a
    LINK   build/test/t-zz0
mkdir -p /Users/sydow/acton/deps/instdir/lib /Users/sydow/acton/deps/instdir/include/bsdnt/arch/inline
cp libbsdnt.a /Users/sydow/acton/deps/instdir/lib
cp config.h helper.h helper_arch.h nn.h nn_arch.h nn_linear_arch.h nn_quadratic_arch.h nn_subquadratic_arch.h rand.h sha1.h test.h tuning.h types_arch.h zz.h zz0.h /Users/sydow/acton/deps/instdir/include/bsdnt
cp arch/inline/nn_linear_x86_64_core2.h arch/inline/nn_linear_x86_64_k8.h /Users/sydow/acton/deps/instdir/include/bsdnt/arch/inline
ls deps/libutf8proc >/dev/null 2>&1 || git clone https://github.com/JuliaStrings/utf8proc.git deps/libutf8proc
Cloning into 'deps/libutf8proc'...
remote: Enumerating objects: 1961, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 1961 (delta 51), reused 84 (delta 38), pack-reused 1850
Receiving objects: 100% (1961/1961), 4.67 MiB | 6.86 MiB/s, done.
Resolving deltas: 100% (1321/1321), done.
mkdir -p deps/instdir/lib/
cd deps/libutf8proc \
	&& git checkout 63f31c908ef7656415f73d6c178f08181239f74c \
	&& make CFLAGS="" \
	&& make install prefix=/Users/sydow/acton/deps/instdir
Note: switching to '63f31c908ef7656415f73d6c178f08181239f74c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 63f31c9 Improve fuzzer code coverage (#239)
cc   -fPIC -std=c99 -Wsign-conversion -Wall -Wextra -pedantic -DUTF8PROC_EXPORTS  -c -o utf8proc.o utf8proc.c
rm -f libutf8proc.a
ar rs libutf8proc.a utf8proc.o
ar: creating archive libutf8proc.a
cc  -dynamiclib -o libutf8proc.2.dylib utf8proc.o -install_name /usr/local/lib/libutf8proc.2.dylib -Wl,-compatibility_version -Wl,2 -Wl,-current_version -Wl,2.5.0
ln -f -s libutf8proc.2.dylib libutf8proc.dylib
sed \
		-e 's#PREFIX#/Users/sydow/acton/deps/instdir#' \
		-e 's#LIBDIR#lib#' \
		-e 's#INCLUDEDIR#include#' \
		-e 's#VERSION#2.5.0#' \
		libutf8proc.pc.in > libutf8proc.pc
mkdir -m 755 -p /Users/sydow/acton/deps/instdir/include
install -m 644 utf8proc.h /Users/sydow/acton/deps/instdir/include
mkdir -m 755 -p /Users/sydow/acton/deps/instdir/lib
install -m 644 libutf8proc.a /Users/sydow/acton/deps/instdir/lib
install -m 755 libutf8proc.2.dylib /Users/sydow/acton/deps/instdir/lib
mkdir -m 755 -p /Users/sydow/acton/deps/instdir/lib/pkgconfig
install -m 644 libutf8proc.pc /Users/sydow/acton/deps/instdir/lib/pkgconfig/libutf8proc.pc
ln -f -s libutf8proc.2.dylib /Users/sydow/acton/deps/instdir/lib/libutf8proc.dylib
ls deps/util-linux >/dev/null 2>&1 || git clone https://github.com/util-linux/util-linux.git deps/util-linux
Cloning into 'deps/util-linux'...
remote: Enumerating objects: 116547, done.
remote: Counting objects: 100% (333/333), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 116547 (delta 172), reused 292 (delta 152), pack-reused 116214
Receiving objects: 100% (116547/116547), 193.20 MiB | 5.16 MiB/s, done.
Resolving deltas: 100% (88483/88483), done.
mkdir -p deps/instdir/lib/
cd deps/util-linux \
	&& git checkout v2.38.1 \
	&& ./autogen.sh \
	&& ./configure --prefix=/Users/sydow/acton/deps/instdir --disable-nls --disable-poman --disable-all-programs --enable-libuuid --enable-static --disable-shared CFLAGS="" \
	&& make -j && make install
Note: switching to 'v2.38.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 54a4d5c3e build-sys: release++ (v2.38.1)

ERROR: You must have autopoint installed to generate the util-linux build system.
       The autopoint command is part of the GNU gettext package.


ERROR: You must have autoconf installed to generate the util-linux build system.


ERROR: You must have autoheader installed to generate the util-linux build system.
       The autoheader command is part of the GNU autoconf package.


WARNING: You need have [x]gettext binary installed to update po/ stuff.


ERROR: You must have libtool-2 installed to generate the util-linux build system.


ERROR: You must have automake installed to generate the util-linux build system.

make: *** [deps/instdir/lib/libuuid.a] Error 1
acton>

**Comment by sydow** [comment]
Hi Kristian,

of course I hadn’t done the brew install…

Now that seems to work! Thank you. 

But I have to understand why math and numpy are not recompiled. The old .o files from  my bigint session yesterday remain in stdlib/out/rel/lib.

I have a vague memory of you talking about this some time ago.

As for pointer_hash.c, I would try to make y unsigned:


long $pointer_hash($WORD p) {
    long x;
    unsigned long y = (unsigned long)p;
    // bottom 3 or 4 bits are likely to be 0; rotate y by 4 to avoid
    //  excessive hash collisions for dicts and sets 
    y = (y >> 4) | (y << 60);
    x = (long)y;
    if (x == -1)
        x = -2;
    return x;
}

 
Björn

**Comment by plajjan** [comment]
@sydow Hmm, not entirely sure but i guess actonc might not catch all updates. Does it work if you do a `make clean` and then make again?

I think the way math & numpy is implemented will go away entirely in preference of the .ext.c style, so I'm inclined not to invest too much time investigating why it didn't do the right thing.

**Comment by plajjan** [comment]
@sydow wow, very cool on the tighter integration & better performance!

This all looks very good. I agree on the hashing part, I opened #1009 for continuing that conversation.

We can continue talking about i64 (and other i/u types) in #793.

**Comment by plajjan** [comment]
I've moved examples/bigint.act to test/builtins_auto/int.act and reworked it to actually test things rather than just print stuff.

Tests pass. Merging as-is. Thanks @sydow for the nice work!

**Pull request merged**
