### PR TITLE
Add `xml` module

### PR DESCRIPTION
**Pull request by plajjan**
This builds on #977.

- fix git history (ugly merge + rebased)
- `examples/xmltest.act` has been replaces by a test in `test/stdlib_auto/test_xml.act`
  - has some simple XML encode / decode tests
- compilation stuff for dependencies is improved, though not complete (run- jobs should fail)

TODO
- [ ] fix access of tag attributes, like `tag.name`, see test_xml.act for TODO & code
- [ ] remove decodeFile
- [ ] rework text handling, remove empty Tags & concatenate read text?
- [ ] squash history & merge

### CODE REVIEW

**Comment by sydow** [comment]
Hi Kristian, 

I am sorry, but I am unable to get git into order. I have tried to enter branch xml, pull there and rebase main, but for me it is impossible. Probably the best thing for me is to give up and clone a new copy of the repository and start again. But I would like to know that if I do this I will not be in a mess of branches named xml and xmlparser linked in (for me) ununderstandable ways. 

Is it correct that I should also delete any traces of libxml2 from my laptop before cloning?

**Comment by plajjan** [comment]
@sydow I'm sorry if I'm the one that messed it up for you... but would you like to do a video call and see if we can sort our the git things?

**Comment by plajjan** [comment]
@sydow and yes, you should be able to delete libxml2 from your system. It shouldn't really affect things I think, because we *should* read in data from our own bundled version of libxml2 first...

**Comment by sydow** [comment]
Hi Kristian, 

I am sure it is not your fault, but everything is due to my inadequate git competence. But I do think that at the moment I am in a situation which is too complicated for me. I am working in two branches (xml and bigint) which both involve not only the code I am writing but the actual Makefile and build process for the software. And then I mess things up. But, sure, a video call may be useful. I am available all afternoon today and almost any time next week. Send a mail as forewarning. I am available on e.g. Facebook; I realise just now that I haven’t yet downloaded Skype to this new laptop. Or we could use Webex…

Björn

**Comment by plajjan** [comment]
Closing this since it will be superseded by work on another branch!

**Pull request closed without merging**
